classifier/urls.py
from django.conf.urls import url, include

from . import views

app_name = "classifier"

urlpatterns = [
    url(r'^home/', views.home, name="home_page"),
    url(r'^profile/(?P<id>[0-9]+)/', views.profile, name="profile_page"),
    url(r'^train/', views.train, name="training_page"),
    url(r'^classifier/(?P<id>[0-9]+)/', views.classifier_detail_view, name="classifier_detail"),
    url(r'^prediction/', views.prediction, name='prediction'),
     # Auth-related URLs:
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^loggedin/$', 'classifier.views.loggedin', name='loggedin'),
    # Registration URLs
    url(r'^register/$', 'classifier.views.register', name='register'),
    url(r'^register/complete/$', 'classifier.views.registration_complete', name='registration_complete'),
    ]

naivebayesters/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'naivebayesters.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^classifier/', include('classifier.urls')),
    url(r'^accounts/', include('classifier.urls')),
]

classifier/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Classifier(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    data = models.TextField()

classifier/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Classifier


class ClassifierForm(forms.ModelForm):
    class Meta:
        model = Classifier
        fields = ('name', 'category', 'data')

classifier/views.py
from django.shortcuts import HttpResponse, render, get_object_or_404, HttpResponseRedirect, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.core.context_processors import csrf
from django.contrib.auth.models import User
from .models import Classifier
from .machine_learning import get_training_data
from .forms import ClassifierForm


# Create your views here.

def loggedin(request):
    return render(request, 'registration/loggedin.html', {'username': request.user.username})

def home(request):
    return render(request, 'home.html')

def profile(request, id):
    owner = User.objects.get(id=id)
    classifier = Classifier.objects.all().filter(owner=owner)
    return render(request, 'profile.html', {'username': request.user.username, 'classifier': classifier})

def train(request):
    if request.method == 'POST':
        form = ClassifierForm(request.POST)
        if form.is_valid():
            classifier = form.save(commit=False)
            classifier.owner = request.user
            classifier.save()
            return HttpResponseRedirect('/classifier/home/')
    else:
        form = ClassifierForm()

    return render(request, 'create.html', {'form': form})

def prediction(request):
    if request.method == 'POST':
        context = {}
        context['test'] = request.POST['test']
        context['testing'] = get_training_data(context['test'])
        return render(request,'prediction.html', context)
    else:
        return render(request,'prediction.html')


def classifier_detail_view(request, id):
    classifier = get_object_or_404(Classifier, pk=id)
    return render(request, 'classifier/detail.html', {'classifier': classifier})

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/accounts/register/complete')

    else:
        form = UserCreationForm()
    token = {}
    token.update(csrf(request))
    token['form'] = form

    return render_to_response('registration/registration_form.html', token)

def registration_complete(request):
    return render(request, 'registration/registration_complete.html')

classifier/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
​

{% block title %}{{ title }} {{ site_title|default:_("NaiveBayesters") }}

{% if request.user.is_anonymous %}
&nbsp;&nbsp; | &nbsp;&nbsp; <a href="/accounts/login">Login</a>
{% endif %}

{% if request.user.is_authenticated %}
&nbsp;&nbsp; | &nbsp;&nbsp;  user: <b>{{request.user.username}}</b>
&nbsp;&nbsp; | &nbsp;&nbsp;  <a href="{% url 'classifier:profile_page' user.id %}">Profile</a>
&nbsp;&nbsp; | &nbsp;&nbsp;  <a href="{% url 'classifier:training_page' %}">New</a>
&nbsp;&nbsp; | &nbsp;&nbsp;  <a href="{% url 'classifier:prediction' %}">Prediction</a>
&nbsp;&nbsp; | &nbsp;&nbsp;  <a href="/accounts/logout">Logout</a>
{% else %}
&nbsp;&nbsp; | &nbsp;&nbsp;  Not logged in.
{% endif %}
{% endblock %}
{% block branding %}
{% endblock %}

{% block nav-global %}{% endblock %}

    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h2>You have logged out</h2>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>

</html>

classifier/templates/classifier/home.html
<!-- This is the template for the homepage which include register and login, wired to /home/ url -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    Login/Register page
  </body>
</html>

classifier/templates/classifier/index.html
{% block content %}


<div class="container">
  <div class="row">
    <br />
    <div class"col-xs-12 col-md-8 col-sm-4">
      <div class="jumbotron">
        <p><b>
          <h2>Welcome to NaiveBayesters.</h2>
        </b></p>
      </div>
    </div>
  </div>
{% endblock %}

classifier/templates/create.html
{% extends "base.html" %}
{% load i18n %}

<!-- This is the template for creating a new classifier, wired to /train/ url -->
<!DOCTYPE html>
{% block content %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Create</title>
  </head>
  <body>
    <h2>Train New Classifier</h2>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <!-- Name:<input type="text" name="name" value=""><br>
      Category:<input type="text" name="category" value=""><br>
      Traning Data:<textarea name="data" rows="8" cols="40"></textarea><br> -->
      <input type="submit" name="submit" value="Create Classifier">
    </form>
  </body>
</html>
{% endblock content %}

classifier/templates/detail.html
<!-- This is the template for a specific classifier, wired to /classifier/<pk>/ url -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ classifier.name }} Classifier</title>
  </head>
  <body>
    Classifier detail page
  </body>
</html>

classifier/templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<!-- This is the template for the homepage which include register and login, wired to /home/ url -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <header>
    <h3>Login</h3>
    Click <a href="/accounts/login">here</a> to log in

    <h3>Not a user?</h3>
    <!-- <div align="right"> -->
    <!-- <a href="/accounts/login">login</a>
    <a href="/accounts/logout">logout</a> -->
    <a href="/accounts/register">Register here!</a>
  </div>
    </header>
  </body>
</html>
{% endblock content %}

classifier/templates/prediction.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
{% if request.user.is_authenticated %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Prediction</title>
  </head>
  <body>
    <h2>Predict a body of text</h2>
    <form class="" action="" method="post">
      {% csrf_token %}
      Text:<textarea name="test" rows="8" cols="40"></textarea><br>
      <input type="submit" name="submit" value="Predict">
    </form>
    {% if testing %}
      <h2>last tested:</h2> {{test}}<br>
      <h2>results:</h2> {{testing}}
    {% endif %}
  </body>
</html>
{% endif %}
{% endblock content %}

classifier/templates/profile.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<!-- This is the template for profile and listing all created classifiers, wired to /profile/ url -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Profile</title>
    <div align="right">
      <a href="/accounts/logout">logout</a>
    </div>
  </head>
  <body>
    <h2>{{username}}'s profile</h2>
    <h3>Created Classifiers</h3>
      <ul>
        {% if classifier %}
          {% for item in classifier %}
            {{item.name}}: {{item.category}}<br>
          {% endfor %}
        {% endif %}
      </ul>

  </body>
</html>

{% endblock content %}